// Importar todos los modelos para registrarlos en Mongoose
import './categoria.model';
import './ciclo.model';
import './contenido.model';
import './estadoPregunta.model';
import './examen.model';
import './examenPregunta.model';
import './intentoExamen.model';
import './nivelDificultad.model';
import './opcionPregunta.model';
import './parEmparejamiento.model';
import './pregunta.model';
import './privilegio.model';
import './rangoEdad.model';
import './respuestaDesarrollo.model';
import './respuestaEmparejamiento.model';
import './respuestaModelo.model';
import './respuestaSeleccion.model';
import './revisionPregunta.model';
import './subcategoria.model';
import './usuario.model';
import './usuarioPrivilegio.model';

export * from './categoria.model';
export * from './ciclo.model';
export * from './contenido.model';
export * from './estadoPregunta.model';
export * from './examen.model';
export * from './examenPregunta.model';
export * from './intentoExamen.model';
export * from './nivelDificultad.model';
export * from './opcionPregunta.model';
export * from './parEmparejamiento.model';
export * from './pregunta.model';
export * from './privilegio.model';
export * from './rangoEdad.model';
export * from './respuestaDesarrollo.model';
export * from './respuestaEmparejamiento.model';
export * from './respuestaModelo.model';
export * from './respuestaSeleccion.model';
export * from './revisionPregunta.model';
export * from './subcategoria.model';
export * from './usuario.model';
export * from './usuarioPrivilegio.model';
